local L = Scorpio("EnhanceBattlefieldMinimap")._Locale("ruRU")
if not L then return end
--Переводчик ZamestoTV
L["reset the zone map"] = "Сбросить карту зоны"
L["on/off/always - embed the minimap"] = "вкл/выкл/всегда - встроить миникарту"
L["r, g, b[, a] - the border's color"] = "r, g, b[, a] - цвет границы"
L["on/off - whether show the zone text"] = "вкл/выкл - показывать название зоны"
L["scale - set the scale of the player arror"] = "масштаб - установить масштаб стрелки игрока"
L["scale - set the scale of the party members"] = "масштаб - установить масштаб членов группы"
L["scale - set the scale of the raid members"] = "масштаб - установить масштаб членов рейда"
L["[0.1-4] - set the scale of the area labels"] = "[0.1-4] - установить масштаб меток области"
L["[0.1-2] - set the scale of the world quest icon, default 0.5"] = "[0.1-2] - установить масштаб значка мировых заданий, по умолчанию 0.5"
L["on/off - toggle the usage of the mouse action"] = "вкл/выкл - переключить использование действий мыши"
L["Lock the map so it can't be resized"] = "Заблокировать карту, чтобы нельзя было изменить размер"
L["Unlock the map so it can be resized"] = "Разблокировать карту для изменения размера"
L["Enable Mouse"] = "Включить взаимодействие мышью"
L["UnLock The Map"] = "Разблокировать карту"
L["Show Zone Text"] = "Показывать название зоны"
L["Embed Minimap"] = "Встроить миникарту"
L["Off"] = "Выкл"
L["On"] = "Вкл"
L["Always"] = "Всегда"
L["Player Scale"] = "Масштаб игрока"
L["Choose Player Scale"] = "Выбрать масштаб игрока"
L["Party Member Scale"] = "Масштаб членов группы"
L["Choose Party Member Scale"] = "Выбрать масштаб членов группы"
L["Raid Member Scale"] = "Масштаб членов рейда"
L["Choose Raid Member Scale"] = "Выбрать масштаб членов рейда"
L["Area Label Scale"] = "Масштаб меток области"
L["Choose Area Label Scale"] = "Выбрать масштаб меток области"
L["World Quest Scale"] = "Масштаб мировых заданий"
L["Choose World Quest Scale"] = "Выбрать масштаб мировых заданий"
L["Border Color"] = "Цвет границы"
L["Only in Battlefield"] = "Только на поле боя"
L["on/off - whether only show in battlegroud"] = "вкл/выкл - показывать только на поле боя"
L["Enable Mouse Coordinate"] = "Показывать координаты мыши"
L["on/off - whether show the coordinate"] = "вкл/выкл - показывать координаты мыши"
L["Minimap"] = "Миникарта"
L["Block Minimap Interaction"] = "Запретить взаимодействие с миникартой при встраивании"
L["on/off - Block the tab frame"] = "вкл/выкл - заблокировать вкладку"
L["Disable The Tab Frame"] = "Отключить вкладку карты"
L["The Frame Strata"] = "Слой интерфейса"
L["Enable the Interaction when mouse over and alt pressed"] = "Включить взаимодействие, когда мышь наведена и нажата клавиша Alt"

L["Pin Texture"] = "Текстура значков"
L["Use Class Color"] = "Использовать цвет класса"
L["Replace Player Arrow"] = "Заменить стрелку игрока"
L["Replace Party Member"] = "Заменить значки членов группы"
L["Replace Raid Member"] = "Заменить значки членов рейда"

L["Enable"] = "Включить"
L["Pin Scale"] = "Масштаб значков"

L["The Minimap Size"] = "Размер миникарты"
L["Choose Minimap Scale"] = "Выбрать размер миникарты"

L["Use Global Profile"] = "Использовать общий профиль"
L["on/off - Use global profile"] = "вкл/выкл - использовать общий профиль"
