local L                         = Scorpio("EnhanceBattlefieldMinimap")._Locale("zhTW")
if not L then return end

L["reset the zone map"]                                           = "重置位置"
L["on/off/always - embed the minimap"]                            = "on/off/always - 內嵌小地圖"
L["r, g, b[, a] - the border's color"]                            = "r, g, b[, a] - 邊框顏色"
L["on/off - whether show the zone text"]                          = "on/off - 是否顯示區域名字"
L["scale - set the scale of the player arror"]                    = "scale - 調整玩家的顯示大小"
L["scale - set the scale of the party members"]                   = "scale - 調整小隊隊員的顯示大小"
L["scale - set the scale of the raid members"]                    = "scale - 調整團隊隊員的顯示大小"
L["[0.1-4] - set the scale of the area labels"]                   = "[0.1-4] - 調整地圖標籤的大小"
L["[0.1-2] - set the scale of the world quest icon, default 0.5"] = "[0.1-2] - 調整世界任務的圖標大小"
L["on/off - toggle the usage of the mouse action"]                = "on/off - 是否啟用鼠標操作"
L["Lock the map so it can't be resized"]                          = "鎖定地圖"
L["Unlock the map so it can be resized"]                          = "解鎖地圖"
L["Enable Mouse"]                                                 = "啟用鼠標交互"
L["UnLock The Map"]                                               = "解鎖地圖"
L["Show Zone Text"]                                               = "顯示區域名稱"
L["Embed Minimap"]                                                = "內嵌小地圖"
L["Off"]                                                          = "關閉"
L["On"]                                                           = "開啟"
L["Always"]                                                       = "總是"
L["Player Scale"]                                                 = "玩家縮放"
L["Choose Player Scale"]                                          = "選擇玩家縮放"
L["Party Member Scale"]                                           = "隊員縮放"
L["Choose Party Member Scale"]                                    = "選擇隊員縮放"
L["Raid Member Scale"]                                            = "團隊成員縮放"
L["Choose Raid Member Scale"]                                     = "選擇團隊成員縮放"
L["Area Label Scale"]                                             = "地圖標籤縮放"
L["Choose Area Label Scale"]                                      = "選擇地圖標籤縮放"
L["World Quest Scale"]                                            = "世界任務縮放"
L["Choose World Quest Scale"]                                     = "選擇選擇地圖標籤縮放"
L["Border Color"]                                                 = "邊框顏色"
L["Only in Battlefield"]                                          = "僅戰場顯示"
L["on/off - whether only show in battlegroud"]                    = "on/off - 是否僅戰場顯示"
L["Enable Mouse Coordinate"]                                      = "顯示鼠標對應坐標"
L["on/off - whether show the coordinate"]                         = "on/off - 是否顯示鼠標對應坐標"
L["Minimap"]                                                      = "小地圖"
L["Block Minimap Interaction"]                                    = "內嵌小地圖時禁止小地圖交互"
L["on/off - Block the tab frame"]                                 = "on/off - 禁用Tab標籤頁"
L["Disable The Tab Frame"]                                        = "禁用地圖Tab標籤頁"
L["The Frame Strata"]                                             = "圖層"
L["Enable the Interaction when mouse over and alt pressed"]       = "僅當鼠標在地圖內並且按下Alt鍵時啟用地圖交互"


L["Pin Texture"]                                                  = "人員材質"
L["Use Class Color"]                                              = "使用職業色"
L["Replace Player Arrow"]                                         = "替換玩家箭頭"
L["Replace Party Member"]                                         = "替換隊伍成員"
L["Replace Raid Member"]                                          = "替換團隊成員"

L["Enable"]                                                       = "啟用"
L["Pin Scale"]                                                    = "圖標縮放"

L["The Minimap Size"]                                             = "小地圖大小"
L["Choose Minimap Scale"]                                         = "選擇小地圖大小"

L["Use Global Profile"]                                           = "使用公用配置"
L["on/off - Use global profile"]                                  = "on/off - 使用公用配置"